server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./infra/config-repo
            - file:./infra/config-repo/main-ru.practicum.service
            - file:./infra/config-repo/stat-server
            - file:./infra/config-repo/gateway-server
            - file:./infra/config-repo/core/user-ru.practicum.service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
