services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6642:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    healthcheck:
      test: pg_isready -q -d stats -U stats
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build: stat/stats-server
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    restart: on-failure

  discovery-server:
    build: ./infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: on-failure

  config-server:
    build: ./infra/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      discovery-server:
        condition: service_started
    restart: on-failure

  gateway-server:
    build: ./infra/gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
    depends_on:
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    restart: on-failure

  users-db:
    image: postgres:16.1
    ports:
      - "6644:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    healthcheck:
      test: pg_isready -q -d users -U users
      timeout: 5s
      interval: 5s
      retries: 10

  requests-db:
    image: postgres:16.1
    ports:
      - "6645:5432"
    environment:
      POSTGRES_DB: requests
      POSTGRES_USER: requests
      POSTGRES_PASSWORD: requests
    healthcheck:
      test: pg_isready -q -d requests -U requests
      timeout: 5s
      interval: 5s
      retries: 10

  events-db:
    image: postgres:16.1
    ports:
      - "6646:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
    healthcheck:
      test: pg_isready -q -d events -U events
      timeout: 5s
      interval: 5s
      retries: 10

  ratings-db:
    image: postgres:16.1
    ports:
      - "6647:5432"
    environment:
      POSTGRES_DB: ratings
      POSTGRES_USER: ratings
      POSTGRES_PASSWORD: ratings
    healthcheck:
      test: pg_isready -q -d ratings -U ratings
      timeout: 5s
      interval: 5s
      retries: 10