server:
  port: 0

spring:
  application:
    name: user-ru.practicum.service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6644/users
    username: users
    password: users

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"