server:
  port: 0

spring:
  application:
    name: rating-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6646/ratings
    username: ratings
    password: ratings

    jpa:
      hibernate:
        ddl-auto: update

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/