server:
  port: 0

stats-server:
  url: http://localhost:9090

spring:
  application:
    name: main-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6643/main
    username: main
    password: main

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"